spring:
  application:
    name: business-service
server:
  port: 8084
management:
  endpoints:
    web:
      exposure:
        include: health,info
resilience4j:
  circuitbreaker:
    instances:
      businessCircuit:
        register-health-indicator: true
        sliding-window-size: 10
        sliding-window-type: count_based
        failure-rate-threshold: 50
        wait-duration-in-open-state: 60s
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
        slow-call-duration-threshold: 3s
